
spring:
# DataSource
  datasource:
    url: jdbc:postgresql://192.168.35.247:5432/recruitment
    username: db
    password: postgres

# JPA
  jpa:
    hibernate:
      ddl-auto: create # update ? ???
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC